### ISSUE TITLE
Unable to push github URL

### ISSUE THREAD

**Issue by anonrose** [rentify/heroku-api#2]
when using the push method heroku-api doesn't recognize that the URL is a GitHub repository and is unable to find it.

```2.2.4 :056 > a.push('https://github.com/g5search/g5-content-management-system/tree/ss-search-sorting')
I, [2017-02-22T08:33:50.922269 #27218]  INFO -- : Starting Git
E, [2017-02-22T08:33:50.922423 #27218] ERROR -- : path does not exist
E, [2017-02-22T08:33:50.922456 #27218] ERROR -- : current_directory/github_directory
```

**Comment by georgedrummond** [comment]
@anonrose this gem is no longer maintained. 

I suggest you use the official [Heroku Platform API Gem](https://github.com/heroku/platform-api) instead.

**Comment by anonrose** [comment]
@georgedrummond I should have noticed the last commit was 3 years ago. Thank you.
